### ISSUE TITLE
Problems with default value	

### ISSUE THREAD

**Issue by agusticonesagago** [dumbre-prasad/react-native-autocomplete-textinput#1]
I would like if you could put an example or explain how to put a default value on the dropdown autcomplete.

Thanky!! :)

**Comment by dumbre-prasad** [comment]
Hi Agusti,

Thanks for trying my autocomplete component, I will get back to you with example asap.

Regards,
Prasad Dumbre

________________________________

**Comment by agusticonesagago** [comment]
Thanky very much!!

Regards,
Agustí Conesa

**Comment by agusticonesagago** [comment]
I have solved the default value problem.

Brilliant autocomplete component!!

Regards,
Agustí Conesa

**Comment by dumbre-prasad** [comment]
Great!!, will you please update the same with github issues

Thanks&Regards
Prasad Dumbre
________________________________
